server:
  port: 8282
  
spring:
  security:
    user:
      name: soumik
      password: soumik123
      roles: ADMIN,USER
      
spring:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      access-token-validity-seconds: 3600
      authorized-grant-types: refresh-token, authorization-code, password, client-credentials
      scope: READ,WRITE
