zuul:
  routes:
    movie-catalog-service:
      path:/catalog/**
      serviceId:MOVIE-CATALOG-SERVICE
    movie-rating-service:
      path:/rating/**
      serviceId:MOVIE-RATING-SERVICE
server:
  port: 8086
  
spring:  application:    name: api-gateway
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

logging:
  level:
    org:
      springframework: INFO
      
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
