server:
  port: 8080
  
spring:  application:    name: movie-catalog-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
